#CPPFLAGS=-I /usr/include/opencv
#LDFLAGS=-L /usr/lib/x86_64-linux-gnu/  -lopencv_core -lopencv_highgui -lopencv_imgproc



cvdemo : main.cpp
	 $(CXX) main.cpp -o cvdemo -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_videoio
all: cvdemo
