/*----- PROTECTED REGION ID(ZedGPIO.h) ENABLED START -----*/
//=============================================================================
//
// file :        ZedGPIO.h
//
// description : Include file for the ZedGPIO class
//
// project :     ZedBoard Tango Gateway
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef ZedGPIO_H
#define ZedGPIO_H

#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	ZedGPIO.h

/**
 *  ZedGPIO class description:
 *    proof of concept :
 *    a tango DS for Zynq with OpenEmbedded toolchain
 */

namespace ZedGPIO_ns
{
/*----- PROTECTED REGION ID(ZedGPIO::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	ZedGPIO::Additional Class Declarations

class ZedGPIO : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(ZedGPIO::Data Members) ENABLED START -----*/

//	Add your own data members

/*----- PROTECTED REGION END -----*/	//	ZedGPIO::Data Members


//	Attribute data members
public:
	Tango::DevUChar	*attr_Switches_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	ZedGPIO(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	ZedGPIO(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	ZedGPIO(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~ZedGPIO() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : ZedGPIO::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : ZedGPIO::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute Switches related methods
 *	Description: 
 *
 *	Data type:	Tango::DevUChar
 *	Attr type:	Scalar
 */
	virtual void read_Switches(Tango::Attribute &attr);
	virtual bool is_Switches_allowed(Tango::AttReqType type);
/**
 *	Attribute Led0 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void write_Led0(Tango::WAttribute &attr);
	virtual bool is_Led0_allowed(Tango::AttReqType type);
/**
 *	Attribute Led1 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void write_Led1(Tango::WAttribute &attr);
	virtual bool is_Led1_allowed(Tango::AttReqType type);
/**
 *	Attribute Led2 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void write_Led2(Tango::WAttribute &attr);
	virtual bool is_Led2_allowed(Tango::AttReqType type);
/**
 *	Attribute Led3 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void write_Led3(Tango::WAttribute &attr);
	virtual bool is_Led3_allowed(Tango::AttReqType type);
/**
 *	Attribute Led4 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void write_Led4(Tango::WAttribute &attr);
	virtual bool is_Led4_allowed(Tango::AttReqType type);
/**
 *	Attribute Led5 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void write_Led5(Tango::WAttribute &attr);
	virtual bool is_Led5_allowed(Tango::AttReqType type);
/**
 *	Attribute Led6 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void write_Led6(Tango::WAttribute &attr);
	virtual bool is_Led6_allowed(Tango::AttReqType type);
/**
 *	Attribute Led7 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void write_Led7(Tango::WAttribute &attr);
	virtual bool is_Led7_allowed(Tango::AttReqType type);
/**
 *	Attribute Leds related methods
 *	Description: 
 *
 *	Data type:	Tango::DevUChar
 *	Attr type:	Scalar
 */
	virtual void write_Leds(Tango::WAttribute &attr);
	virtual bool is_Leds_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : ZedGPIO::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command Start related method
	 *	Description: 
	 *
	 */
	virtual void start();
	virtual bool is_Start_allowed(const CORBA::Any &any);
	/**
	 *	Command Stop related method
	 *	Description: 
	 *
	 */
	virtual void stop();
	virtual bool is_Stop_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : ZedGPIO::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(ZedGPIO::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	ZedGPIO::Additional Method prototypes
};

/*----- PROTECTED REGION ID(ZedGPIO::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	ZedGPIO::Additional Classes Definitions

}	//	End of namespace

#endif   //	ZedGPIO_H
