/*----- PROTECTED REGION ID(AmpereHourMeter.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        AmpereHourMeter.cpp
//
// description : C++ source for the AmpereHourMeter class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               AmpereHourMeter are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <AmpereHourMeter.h>
#include <AmpereHourMeterClass.h>
#include <fcntl.h> //open
#include <unistd.h> //close
#include <sys/mman.h> //mmap
#include <stdio.h>
#include <stdint.h>
/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter.cpp

/**
 *  AmpereHourMeter class description:
 *    - live current measure
 *    - sum
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//  On            |  on
//  Off           |  off
//  Reset         |  reset
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  Current    |  Tango::DevDouble	Scalar
//  AmperHour  |  Tango::DevDouble	Scalar
//================================================================

namespace AmpereHourMeter_ns
{
/*----- PROTECTED REGION ID(AmpereHourMeter::namespace_starting) ENABLED START -----*/

//	static initializations
void* ocm = NULL;
/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : AmpereHourMeter::AmpereHourMeter()
 *	Description : Constructors for a Tango device
 *                implementing the classAmpereHourMeter
 */
//--------------------------------------------------------
AmpereHourMeter::AmpereHourMeter(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(AmpereHourMeter::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::constructor_1
}
//--------------------------------------------------------
AmpereHourMeter::AmpereHourMeter(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(AmpereHourMeter::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::constructor_2
}
//--------------------------------------------------------
AmpereHourMeter::AmpereHourMeter(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(AmpereHourMeter::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : AmpereHourMeter::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void AmpereHourMeter::delete_device()
{
	DEBUG_STREAM << "AmpereHourMeter::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(AmpereHourMeter::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::delete_device
	delete[] attr_Current_read;
	delete[] attr_AmperHour_read;
}

//--------------------------------------------------------
/**
 *	Method      : AmpereHourMeter::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void AmpereHourMeter::init_device()
{
	DEBUG_STREAM << "AmpereHourMeter::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(AmpereHourMeter::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::init_device_before
	
	//	No device property to be read from database
	
	attr_Current_read = new Tango::DevDouble[1];
	attr_AmperHour_read = new Tango::DevDouble[1];
	/*----- PROTECTED REGION ID(AmpereHourMeter::init_device) ENABLED START -----*/
	
	//	Initialize device
	set_state(Tango::OFF);

	int memf = open("/dev/mem", O_RDWR | O_SYNC );
	if(memf < 0) {printf("mem error\n\r");}
        ocm = mmap(NULL, 1024, PROT_READ | PROT_WRITE, MAP_SHARED, memf,0xFFFF0000);
	if(ocm == MAP_FAILED) {printf("mmpa error\n\r"); }
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::init_device
}


//--------------------------------------------------------
/**
 *	Method      : AmpereHourMeter::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void AmpereHourMeter::always_executed_hook()
{
	DEBUG_STREAM << "AmpereHourMeter::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(AmpereHourMeter::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : AmpereHourMeter::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void AmpereHourMeter::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "AmpereHourMeter::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(AmpereHourMeter::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute Current related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void AmpereHourMeter::read_Current(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmpereHourMeter::read_Current(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmpereHourMeter::read_Current) ENABLED START -----*/
	//	Set the attribute value
	*attr_Current_read=*((float*)ocm);
	attr.set_value(attr_Current_read);
	
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::read_Current
}
//--------------------------------------------------------
/**
 *	Read attribute AmperHour related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void AmpereHourMeter::read_AmperHour(Tango::Attribute &attr)
{
	DEBUG_STREAM << "AmpereHourMeter::read_AmperHour(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(AmpereHourMeter::read_AmperHour) ENABLED START -----*/
	//	Set the attribute value
	*attr_AmperHour_read=*(((float*)ocm)+1);
	attr.set_value(attr_AmperHour_read);
	
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::read_AmperHour
}

//--------------------------------------------------------
/**
 *	Method      : AmpereHourMeter::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void AmpereHourMeter::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(AmpereHourMeter::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command On related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void AmpereHourMeter::on()
{
	DEBUG_STREAM << "AmpereHourMeter::On()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmpereHourMeter::on) ENABLED START -----*/
	
	//	Add your own code
	set_state(Tango::ON);
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::on
}
//--------------------------------------------------------
/**
 *	Command Off related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void AmpereHourMeter::off()
{
	DEBUG_STREAM << "AmpereHourMeter::Off()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmpereHourMeter::off) ENABLED START -----*/
	
	//	Add your own code
	set_state(Tango::OFF);
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::off
}
//--------------------------------------------------------
/**
 *	Command Reset related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void AmpereHourMeter::reset()
{
	DEBUG_STREAM << "AmpereHourMeter::Reset()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(AmpereHourMeter::reset) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::reset
}
//--------------------------------------------------------
/**
 *	Method      : AmpereHourMeter::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void AmpereHourMeter::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(AmpereHourMeter::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::add_dynamic_commands
}

/*----- PROTECTED REGION ID(AmpereHourMeter::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	AmpereHourMeter::namespace_ending
} //	namespace
