/*----- PROTECTED REGION ID(RedpitayaStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        RedpitayaStateMachine.cpp
//
// description : State machine file for the Redpitaya class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Redpitaya.h>

/*----- PROTECTED REGION END -----*/	//	Redpitaya::RedpitayaStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  OFF     |  


namespace Redpitaya_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Redpitaya::is_Led0_allowed()
 *	Description : Execution allowed for Led0 attribute
 */
//--------------------------------------------------------
bool Redpitaya::is_Led0_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(Redpitaya::Led0StateAllowed_WRITE) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	Redpitaya::Led0StateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Redpitaya::is_Led1_allowed()
 *	Description : Execution allowed for Led1 attribute
 */
//--------------------------------------------------------
bool Redpitaya::is_Led1_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(Redpitaya::Led1StateAllowed_WRITE) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	Redpitaya::Led1StateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Redpitaya::is_Led2_allowed()
 *	Description : Execution allowed for Led2 attribute
 */
//--------------------------------------------------------
bool Redpitaya::is_Led2_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(Redpitaya::Led2StateAllowed_WRITE) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	Redpitaya::Led2StateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Redpitaya::is_Led3_allowed()
 *	Description : Execution allowed for Led3 attribute
 */
//--------------------------------------------------------
bool Redpitaya::is_Led3_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(Redpitaya::Led3StateAllowed_WRITE) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	Redpitaya::Led3StateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Redpitaya::is_Led4_allowed()
 *	Description : Execution allowed for Led4 attribute
 */
//--------------------------------------------------------
bool Redpitaya::is_Led4_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(Redpitaya::Led4StateAllowed_WRITE) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	Redpitaya::Led4StateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Redpitaya::is_Led5_allowed()
 *	Description : Execution allowed for Led5 attribute
 */
//--------------------------------------------------------
bool Redpitaya::is_Led5_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(Redpitaya::Led5StateAllowed_WRITE) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	Redpitaya::Led5StateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Redpitaya::is_Led6_allowed()
 *	Description : Execution allowed for Led6 attribute
 */
//--------------------------------------------------------
bool Redpitaya::is_Led6_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(Redpitaya::Led6StateAllowed_WRITE) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	Redpitaya::Led6StateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Redpitaya::is_Led7_allowed()
 *	Description : Execution allowed for Led7 attribute
 */
//--------------------------------------------------------
bool Redpitaya::is_Led7_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(Redpitaya::Led7StateAllowed_WRITE) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	Redpitaya::Led7StateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Redpitaya::is_Signal0_allowed()
 *	Description : Execution allowed for Signal0 attribute
 */
//--------------------------------------------------------
bool Redpitaya::is_Signal0_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(Redpitaya::Signal0StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Redpitaya::Signal0StateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Redpitaya::is_Signal1_allowed()
 *	Description : Execution allowed for Signal1 attribute
 */
//--------------------------------------------------------
bool Redpitaya::is_Signal1_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(Redpitaya::Signal1StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Redpitaya::Signal1StateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Redpitaya::is_Decimation_allowed()
 *	Description : Execution allowed for Decimation attribute
 */
//--------------------------------------------------------
bool Redpitaya::is_Decimation_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Decimation command.
	/*----- PROTECTED REGION ID(Redpitaya::DecimationStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Redpitaya::DecimationStateAllowed
	return true;
}

}	//	End of namespace
