/*----- PROTECTED REGION ID(RedpitayaClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        RedpitayaClass.cpp
//
// description : C++ source for the RedpitayaClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the Redpitaya once per process.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <RedpitayaClass.h>

/*----- PROTECTED REGION END -----*/	//	RedpitayaClass.cpp

//-------------------------------------------------------------------
/**
 *	Create RedpitayaClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_Redpitaya_class(const char *name) {
		return Redpitaya_ns::RedpitayaClass::init(name);
	}
}

namespace Redpitaya_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
RedpitayaClass *RedpitayaClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		RedpitayaClass::RedpitayaClass(string &s)
 * description : 	constructor for the RedpitayaClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
RedpitayaClass::RedpitayaClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering RedpitayaClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(RedpitayaClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RedpitayaClass::constructor

	cout2 << "Leaving RedpitayaClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		RedpitayaClass::~RedpitayaClass()
 * description : 	destructor for the RedpitayaClass
 */
//--------------------------------------------------------
RedpitayaClass::~RedpitayaClass()
{
	/*----- PROTECTED REGION ID(RedpitayaClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RedpitayaClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		RedpitayaClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
RedpitayaClass *RedpitayaClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new RedpitayaClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		RedpitayaClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
RedpitayaClass *RedpitayaClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		DecimationClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *DecimationClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "DecimationClass::execute(): arrived" << endl;
	Tango::DevShort argin;
	extract(in_any, argin);
	((static_cast<Redpitaya *>(device))->decimation(argin));
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : RedpitayaClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum RedpitayaClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : RedpitayaClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum RedpitayaClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : RedpitayaClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum RedpitayaClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : RedpitayaClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void RedpitayaClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
}

//--------------------------------------------------------
/**
 *	Method      : RedpitayaClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void RedpitayaClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("Redpitaya");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : RedpitayaClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void RedpitayaClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(RedpitayaClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RedpitayaClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Redpitaya(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Redpitaya *dev = static_cast<Redpitaya *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(RedpitayaClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RedpitayaClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : RedpitayaClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void RedpitayaClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(RedpitayaClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RedpitayaClass::attribute_factory_before
	//	Attribute : Led0
	Led0Attrib	*led0 = new Led0Attrib();
	Tango::UserDefaultAttrProp	led0_prop;
	//	description	not set for Led0
	//	label	not set for Led0
	//	unit	not set for Led0
	//	standard_unit	not set for Led0
	//	display_unit	not set for Led0
	//	format	not set for Led0
	//	max_value	not set for Led0
	//	min_value	not set for Led0
	//	max_alarm	not set for Led0
	//	min_alarm	not set for Led0
	//	max_warning	not set for Led0
	//	min_warning	not set for Led0
	//	delta_t	not set for Led0
	//	delta_val	not set for Led0
	
	led0->set_default_properties(led0_prop);
	//	Not Polled
	led0->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(led0);

	//	Attribute : Led1
	Led1Attrib	*led1 = new Led1Attrib();
	Tango::UserDefaultAttrProp	led1_prop;
	//	description	not set for Led1
	//	label	not set for Led1
	//	unit	not set for Led1
	//	standard_unit	not set for Led1
	//	display_unit	not set for Led1
	//	format	not set for Led1
	//	max_value	not set for Led1
	//	min_value	not set for Led1
	//	max_alarm	not set for Led1
	//	min_alarm	not set for Led1
	//	max_warning	not set for Led1
	//	min_warning	not set for Led1
	//	delta_t	not set for Led1
	//	delta_val	not set for Led1
	
	led1->set_default_properties(led1_prop);
	//	Not Polled
	led1->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(led1);

	//	Attribute : Led2
	Led2Attrib	*led2 = new Led2Attrib();
	Tango::UserDefaultAttrProp	led2_prop;
	//	description	not set for Led2
	//	label	not set for Led2
	//	unit	not set for Led2
	//	standard_unit	not set for Led2
	//	display_unit	not set for Led2
	//	format	not set for Led2
	//	max_value	not set for Led2
	//	min_value	not set for Led2
	//	max_alarm	not set for Led2
	//	min_alarm	not set for Led2
	//	max_warning	not set for Led2
	//	min_warning	not set for Led2
	//	delta_t	not set for Led2
	//	delta_val	not set for Led2
	
	led2->set_default_properties(led2_prop);
	//	Not Polled
	led2->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(led2);

	//	Attribute : Led3
	Led3Attrib	*led3 = new Led3Attrib();
	Tango::UserDefaultAttrProp	led3_prop;
	//	description	not set for Led3
	//	label	not set for Led3
	//	unit	not set for Led3
	//	standard_unit	not set for Led3
	//	display_unit	not set for Led3
	//	format	not set for Led3
	//	max_value	not set for Led3
	//	min_value	not set for Led3
	//	max_alarm	not set for Led3
	//	min_alarm	not set for Led3
	//	max_warning	not set for Led3
	//	min_warning	not set for Led3
	//	delta_t	not set for Led3
	//	delta_val	not set for Led3
	
	led3->set_default_properties(led3_prop);
	//	Not Polled
	led3->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(led3);

	//	Attribute : Led4
	Led4Attrib	*led4 = new Led4Attrib();
	Tango::UserDefaultAttrProp	led4_prop;
	//	description	not set for Led4
	//	label	not set for Led4
	//	unit	not set for Led4
	//	standard_unit	not set for Led4
	//	display_unit	not set for Led4
	//	format	not set for Led4
	//	max_value	not set for Led4
	//	min_value	not set for Led4
	//	max_alarm	not set for Led4
	//	min_alarm	not set for Led4
	//	max_warning	not set for Led4
	//	min_warning	not set for Led4
	//	delta_t	not set for Led4
	//	delta_val	not set for Led4
	
	led4->set_default_properties(led4_prop);
	//	Not Polled
	led4->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(led4);

	//	Attribute : Led5
	Led5Attrib	*led5 = new Led5Attrib();
	Tango::UserDefaultAttrProp	led5_prop;
	//	description	not set for Led5
	//	label	not set for Led5
	//	unit	not set for Led5
	//	standard_unit	not set for Led5
	//	display_unit	not set for Led5
	//	format	not set for Led5
	//	max_value	not set for Led5
	//	min_value	not set for Led5
	//	max_alarm	not set for Led5
	//	min_alarm	not set for Led5
	//	max_warning	not set for Led5
	//	min_warning	not set for Led5
	//	delta_t	not set for Led5
	//	delta_val	not set for Led5
	
	led5->set_default_properties(led5_prop);
	//	Not Polled
	led5->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(led5);

	//	Attribute : Led6
	Led6Attrib	*led6 = new Led6Attrib();
	Tango::UserDefaultAttrProp	led6_prop;
	//	description	not set for Led6
	//	label	not set for Led6
	//	unit	not set for Led6
	//	standard_unit	not set for Led6
	//	display_unit	not set for Led6
	//	format	not set for Led6
	//	max_value	not set for Led6
	//	min_value	not set for Led6
	//	max_alarm	not set for Led6
	//	min_alarm	not set for Led6
	//	max_warning	not set for Led6
	//	min_warning	not set for Led6
	//	delta_t	not set for Led6
	//	delta_val	not set for Led6
	
	led6->set_default_properties(led6_prop);
	//	Not Polled
	led6->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(led6);

	//	Attribute : Led7
	Led7Attrib	*led7 = new Led7Attrib();
	Tango::UserDefaultAttrProp	led7_prop;
	//	description	not set for Led7
	//	label	not set for Led7
	//	unit	not set for Led7
	//	standard_unit	not set for Led7
	//	display_unit	not set for Led7
	//	format	not set for Led7
	//	max_value	not set for Led7
	//	min_value	not set for Led7
	//	max_alarm	not set for Led7
	//	min_alarm	not set for Led7
	//	max_warning	not set for Led7
	//	min_warning	not set for Led7
	//	delta_t	not set for Led7
	//	delta_val	not set for Led7
	
	led7->set_default_properties(led7_prop);
	//	Not Polled
	led7->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(led7);

	//	Attribute : Signal0
	Signal0Attrib	*signal0 = new Signal0Attrib();
	Tango::UserDefaultAttrProp	signal0_prop;
	//	description	not set for Signal0
	//	label	not set for Signal0
	//	unit	not set for Signal0
	//	standard_unit	not set for Signal0
	//	display_unit	not set for Signal0
	//	format	not set for Signal0
	//	max_value	not set for Signal0
	//	min_value	not set for Signal0
	//	max_alarm	not set for Signal0
	//	min_alarm	not set for Signal0
	//	max_warning	not set for Signal0
	//	min_warning	not set for Signal0
	//	delta_t	not set for Signal0
	//	delta_val	not set for Signal0
	
	signal0->set_default_properties(signal0_prop);
	//	Not Polled
	signal0->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(signal0);

	//	Attribute : Signal1
	Signal1Attrib	*signal1 = new Signal1Attrib();
	Tango::UserDefaultAttrProp	signal1_prop;
	//	description	not set for Signal1
	//	label	not set for Signal1
	//	unit	not set for Signal1
	//	standard_unit	not set for Signal1
	//	display_unit	not set for Signal1
	//	format	not set for Signal1
	//	max_value	not set for Signal1
	//	min_value	not set for Signal1
	//	max_alarm	not set for Signal1
	//	min_alarm	not set for Signal1
	//	max_warning	not set for Signal1
	//	min_warning	not set for Signal1
	//	delta_t	not set for Signal1
	//	delta_val	not set for Signal1
	
	signal1->set_default_properties(signal1_prop);
	//	Not Polled
	signal1->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(signal1);

	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(RedpitayaClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RedpitayaClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : RedpitayaClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void RedpitayaClass::command_factory()
{
	/*----- PROTECTED REGION ID(RedpitayaClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RedpitayaClass::command_factory_before


	//	Command Decimation
	DecimationClass	*pDecimationCmd =
		new DecimationClass("Decimation",
			Tango::DEV_SHORT, Tango::DEV_VOID,
			"decimation factor, legal values: 0--5\n1, 8, 64, 1024, 8192, 65536",
			"",
			Tango::OPERATOR);
	command_list.push_back(pDecimationCmd);

	/*----- PROTECTED REGION ID(RedpitayaClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RedpitayaClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		RedpitayaClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void RedpitayaClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(RedpitayaClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RedpitayaClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		RedpitayaClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void RedpitayaClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		Redpitaya *dev = static_cast<Redpitaya *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(RedpitayaClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RedpitayaClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : RedpitayaClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *RedpitayaClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; it++)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(RedpitayaClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	RedpitayaClass::Additional Methods
} //	namespace
